## Numpy

수치해석용 파이썬 패키지

#### [ NumPy 배열 (array) ]

- 리스트와 차이점<br>
모든 원소가 같은 자료형.<br>
원소의 수 변경 불가능<br>
리스트보다 적은 메모리사용. 빠른 처리<br>
다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원<br>
벡터와 행렬을 사용하는 선형대수 계산에 주로 사용

In [10]:
import numpy as np

#### [ 1차원 배열 만들기 ]

NumPy의 array라는 함수에 리스트를 넣으면 배열로 변환

In [11]:
data = [0,1,2,3,4,5,6,7,8,9]
x = #TODO
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### [벡터화 연산]

배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리

In [12]:
# 벡터 연산
x = #TODO
x  

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Cf. 일반적인 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼으로 증가


In [15]:
data = [0,1,2,3,4,5,6,7,8,9]
print#TODO 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
# 벡터 연산
a = np.array( [1,2,3])
b = np.array( [10,20,30] )
print (#TODO  )
print (#TODO  )
print (b > 10 )
print ( (a==2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


#### [2차원 배열 만들기 ]

2차원 배열은 행렬(matrix) <br>
가로줄을 행(row) 세로줄을 열(column)

In [19]:
#행렬
c = #TODO( [  [0,1,2], [3,4,5]  ])
print( #TODO(c) )  #행의 수
print(c )

2
[[0 1 2]
 [3 4 5]]


#### [3차원 배열 만들기 ]

In [23]:
d = np.array( [[[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]],
               [[11,12,13,14] ,
                 [15,16,17,18],
                 [19,20,21,22]]] 
)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

#### [배열의 차원과 크기 알아내기 ]

dim 속성은 배열의 차원, shape 속성은 배열의 크기를 반환

In [24]:
print( #TODO) # 차원
print( #TODO )

3
(2, 3, 4)


In [25]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.#TODO)
print(c.#TODO)

2
(2, 3)


문제1)  NumPy를 사용하여 다음과 같은 2차원 행렬을 만든다.<br> 
 <br>
10 20 30 40 <br> 
50 60 70 80 <br> 

문제2)위 행렬의 모든 값에 3을 더하고, 10을 곱하여 출력. <br> 

In [ ]:
#답01)
 #TODO
#답02)
 #TODO

문제3) <br> 
m = np.array([[ 0,  1,  2,  3,  4], <br>
              [ 5,  6,  7,  8,  9],  <br> <br>
              [10, 11, 12, 13, 14]]) <br>
1.	이 행렬에서 값 7 을 인덱싱 <br>
2.	이 행렬에서 값 14 을 인덱싱 <br>
3.	이 행렬에서 배열 [6, 7] 을 슬라이싱 <br>
4.	이 행렬에서 배열 [7, 12] 을 슬라이싱 <br>
5.	이 행렬에서 배열 [[3, 4], [8, 9]]을 슬라이싱 <br>

In [ ]:
#답3)
 

문제4) <br> 
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,  <br> 
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) <br> 
1.	이 배열에서 3의 배수를 찾아라. <br> 
2.	이 배열에서 4로 나누면 1이 남는 수를 찾아라. <br> 
3.	이 배열에서 3으로 나눈 나머지는 0이고, 4로 나누면 1이 남는 수를 찾아라 <br> 


In [27]:
#답4)
 

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


#### [배열의 인덱싱]

In [30]:
a = np.array([0, 1, 2, 3, 4])
print(a[0], a[-1] )         # 첫번째 , 마지막번째

0 4


In [32]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0, 0] )    # 첫번째 행의 첫번째 열
print(a[-1, -1] )  # 마지막 행의 마지막 열

0
5


#### [배열의 슬라이싱]

In [33]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[0, :] ) # 0 행 모든열
print(a[: , 0] ) # 모든행 0 열
print(a[0:2, :-1] ) #0 행~1 행, 처음부터 마지막열까지

[0 1 2 3]
[0 4]
[[0 1 2]
 [4 5 6]]


In [34]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print( a % 2 )
print(a % 2 == 0 )
print(a[a % 2 == 0])
print(a)
a = a[a % 2 == 0]
print(a) 

[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


#### [전치 연산 ]]

2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 것.


In [35]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
